In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
train = pd.read_csv('database.csv')

In [4]:
train = train.iloc[:,1:3]

In [8]:
train.iloc[0,1]

'[[ 0.08544662  0.08217926 -0.09790755  0.02081523  0.12592678  0.16980924\n   0.05333363 -0.07954034 -0.05556595 -0.01815041  0.05616137  0.10963549\n   0.08840775 -0.09690296  0.01762472 -0.02107712  0.00542801 -0.02055292\n  -0.07609457  0.21337767  0.01193375 -0.04306478  0.00975703  0.13715518\n  -0.00646998 -0.09132435 -0.06759106 -0.10606112 -0.00634268  0.1328382\n  -0.02656963  0.02561797  0.00480812  0.10170562 -0.01547329  0.06443619\n   0.04974547  0.00340857 -0.03653977 -0.06218025  0.05187165 -0.09749981\n   0.05541167 -0.03702895 -0.12448993  0.04333816  0.13303027  0.04544321\n  -0.14939763  0.11927571 -0.02408346 -0.09728833 -0.01222838  0.00232736\n   0.11516358  0.03348882 -0.1796391   0.11549123 -0.11222926  0.00523056\n  -0.11893165  0.05364279  0.1777493  -0.24840651  0.09404111  0.04637172\n  -0.03052753  0.01717933 -0.23640947 -0.08177546  0.01027978  0.04511116\n  -0.07831548 -0.01852695  0.08412152  0.12644708  0.09080614  0.00646773\n   0.07330097  0.06332686 -0.01573018 -0.02397515 -0.05946408 -0.00256511\n  -0.04927693  0.08332517 -0.0245223  -0.01541022  0.02257206  0.16960075\n   0.07983872 -0.19614622 -0.02956947  0.1472553  -0.07667388 -0.03097779\n  -0.04014822 -0.06417457  0.05014655 -0.04445663  0.02887547 -0.02156468\n  -0.08974019  0.01977091 -0.14725837  0.16883384 -0.04445227  0.06142063\n  -0.09210075  0.03221052  0.06047677  0.08612079  0.04502589  0.02845231\n  -0.033282    0.01127071 -0.15982005  0.05766122 -0.04222927  0.17595518\n   0.00231173 -0.05578507  0.01314161  0.0993902   0.0211722   0.13313468\n   0.00662116 -0.16694114]]'

In [10]:
train.iloc[1,1]

'[[ 0.08103063 -0.01219649 -0.07123775 -0.02880255  0.0331933   0.11506484\n  -0.02883272  0.00578551 -0.06334937 -0.0925537   0.06961757 -0.0319867\n   0.08810955  0.16035296  0.18469381 -0.15932892  0.0448037  -0.1819911\n   0.09018584  0.12176557 -0.09670528  0.01010125  0.07561968  0.04669607\n   0.04820806 -0.05051947  0.00230647 -0.00973202 -0.0233243  -0.04844484\n   0.10162126 -0.10744502  0.00430732 -0.00418532 -0.05327524  0.17772989\n   0.0061604   0.06980971 -0.03268596  0.04383215  0.06659213  0.04760608\n  -0.15433846 -0.04252252 -0.17185397  0.04998382 -0.00725225  0.05559871\n   0.04485248  0.0498484  -0.17889786  0.04226502  0.07182506  0.01636338\n   0.01682026 -0.01673112 -0.11557707  0.14954014 -0.03663861 -0.03653416\n  -0.18798356  0.09378327  0.10801055 -0.14574675 -0.0428685   0.16164444\n   0.17005385  0.11835929 -0.01052267 -0.07852955  0.08651674  0.07213983\n  -0.00025431  0.01081568  0.16984354  0.03194617 -0.06292833 -0.11422849\n   0.08022726  0.1754447  -0.02954358 -0.07128419  0.00577119 -0.07814632\n   0.03629063  0.02724685  0.02593172 -0.00502141 -0.00753595 -0.03186663\n   0.12494706 -0.06449123  0.1185369   0.05952149 -0.05564621 -0.21905565\n   0.00612463 -0.04768531  0.00640822 -0.09032228 -0.06773861  0.03794774\n   0.02772756 -0.07450948 -0.23030101  0.21346888 -0.01939672 -0.02325121\n   0.03049523 -0.0087512   0.13949592  0.05901374 -0.01363381  0.02360504\n  -0.06219396  0.03414288 -0.09714043 -0.02179019  0.01349979  0.08150728\n  -0.01219773 -0.11945615 -0.06182706  0.10609766 -0.02343679  0.05532714\n   0.02736537  0.06959417]]'

In [38]:
database = {}
for i in range(len(train)):
	k = train.iloc[i,1].split()
	k = k[1:]
	x = k[-1]
	x = x[:-2]
	k[-1] = float(x)
	database[train.iloc[i,0]] = np.array(k,dtype='float64')

In [42]:
for k,v in database.items():
    print(v[-1])

-0.16694114
0.06959417
-0.10859919
-0.14478879
-0.00927677937
-0.08822514
-0.11858001
-0.09919953
-0.130013883
-0.0895742774
-0.09238757
-0.16425353

In [27]:
x = database["Anshuman"][-1]

In [28]:
x

'-0.16694114]]'

In [32]:
x[:-2]

'-0.16694114'

In [43]:
test = pd.read_csv('testData.csv')

In [44]:
test = test.iloc[:,1:3]

In [45]:
test

      0                                                  1
0    me  [[ 0.09722305  0.13914385 -0.07299903 -0.02299...
1   t10  [[ 0.11423574  0.14133465  0.09675921  0.05179...
2   t11  [[ 1.16491817e-01 -1.56117789e-03  2.02352889e...
3   t12  [[ 0.04808855  0.13542525 -0.05100951 -0.02770...
4   t13  [[ 0.1338325   0.01104283  0.08723535  0.08323...
5   t14  [[ 1.42344549e-01 -3.60911377e-02 -7.71049932e...
6    t1  [[ 0.01872638  0.18900451  0.04040387  0.06608...
7    t2  [[ 4.73748669e-02  1.79597825e-01  2.44046506e...
8    t3  [[ 0.11081789  0.07956336 -0.06240524 -0.01621...
9    t4  [[ 0.04327407  0.12800649 -0.04298423  0.00278...
10   t5  [[ 1.70288816e-01  6.20462745e-02 -6.53468370e...
11   t6  [[ 6.14158101e-02  1.63969491e-02 -1.65136550e...
12   t7  [[ 0.14304514  0.02532584  0.04861048 -0.02099...
13   t8  [[ 0.12955451  0.0755508  -0.06182517  0.00922...
14  t91  [[ 0.10900261  0.20354162 -0.05769982 -0.01461...
15  t92  [[ 1.63586527e-01  1.07219838e-01  1.89693703e...

In [58]:
testData= {}
for i in range(len(test)):
	k = test.iloc[i,1].split()
	k = k[1:]
	if k[-1]==']]':
		k = k[:-1]
	else:
		x = k[-1]
		x = x[:-2]
		k[-1] =  float(x)
	testData[test.iloc[i,0]] = k
	#print(k)

In [59]:
for k,v in testData.items():
    print(str(v[-1]) + " " + str(len(v)))

-0.1682781 128
-0.17432626 128
-0.132746786 128
-0.1236635 128
-0.17004625 128
-0.199539647 128
-0.0484027 128
-0.0773052797 128
-0.20204169 128
-0.02138881 128
-0.207483411 128
-0.0861325338 128
-0.14876817 128
-0.12283792 128
-0.13397337 128
-0.142605096 128

In [96]:
for k,v in testData.items():

-0.1682781
-0
-1
-0.1236635
-0
-1
-0.0484027
-7
-0
-0
-2
-8
-0
-0
-0
-1

In [91]:
for k,v in database.items():
    print(len(v))

128
128
128
128
128
128
128
128
128
128
128
128